### ISSUE TITLE
Umfrage: Styling bugs fixen

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#100]
Es gibt mehrere "Bugs":
- Wenn man in seiner Auswahl eine leere Priorität hat wird auch bei der Umfrage ein leeres kästchen incl. umfrage angezeigt.
-  "Die Thematik ist leicht verständlich" un "Sonstiges" haben einen merkwürdigen zeilen-umbruch.
-  Die rechte Spalte der Auswahlmöglichkeiten ist nicht in einer linie

**Comment by BenSauerlaender** [comment]
Die bugs sind teilweise gekommen, da ich #75 in dev gemerged habe. @jimmy080900 mach das nächstes mal bitte direkt. dann treten auch keine conflicts auf.

**Comment by jimmy080900** [comment]
Styling bugs sind behoben und in Dev gepushed
