### ISSUE TITLE
Kursbelegnung polishen

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#105]
- "kurbelegung erstellen" entfernen -> soll automatisch passieren
- So ändern, dass IMMER genau eine leere prio da ist.
- prio hinzufügen / löschen entfernen
- in leeren prios: text: "Hier kurs reinziehen" (oder änliches)
- max Kurse ändern zu gewünschte Kursanzahl
- maxKurse-speicher problematik lösen.
- bug fixen, das man markierte kures rüberziehen kann, obwohl gespeichert wurde.

**Comment by ChuChuPL** [comment]
Fertig:

Default values 
"kurbelegung erstellen" entfernen -> soll automatisch passieren
So ändern, dass IMMER genau eine leere prio da ist.
prio hinzufügen  entfernen //löschen soll bleiben
maxCourse anpassen an neues Modell 

Anmerkung:
Jetzt ist min für maxCourses bei 1
