### ISSUE TITLE
Die Studiengangs-Option IMI-M rausnehmen?

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#107]
Da wir aktuell den Master nicht in der Kurswahl unterstützen.

**Comment by ChuChuPL** [comment]
ich würde den vielleicht da lassen, weil der studyplan von julia auch benutzt werden kann.
aber was haltet ihr davon

**Comment by BenSauerlaender** [comment]
lassen wir drinn
