### ISSUE TITLE
Möglichkeit vergessenen Benutzernamen anzufragen bzw. Benutzernamen entfernen

### ISSUE THREAD

**Issue by nt2743** [modulehandbook/studyplan#110]
Wenn man seinen Benutzernamen vergisst, gibt es keine Möglichkeit diesen irgendwo anzufragen. Am besten wäre es wenn der Benutzername ganz wegfällt, da er soweit ich das sehe auch keinen wirklichen Nutzen hat.

**Comment by nosch41** [comment]
Der Login ist jetzt auch per Emailadresse möglich
