### ISSUE TITLE
Der Verifikationslink führt auf hässliche Seite ohne link zum login

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#111]
Wenn man sich registriert, und auf den Verifikationslink klickt kommt man auf eine most basic html seite, auf der zwar die URL zum login steht, die aber kein link ist.

**Comment by nosch41** [comment]
Mit commit 63786c92 hat sich Folgendes geändert: Man kommt auf eine HTML Seite mit clickbarem Login-Link. Zum Login wird man automatisch nach 3 Sekunden weitergeleitet
