### ISSUE TITLE
Mailer und Authentifizierung implementieren

### ISSUE THREAD

**Issue by LennoxCode** [modulehandbook/studyplan#16]
momentan ist im StudyPlan noch ein mailer mit einem Token implementiert, auf das wir keinen Zugriff haben. Es muss also durch eine neue Gmail adresse ersetzt werden und nachdem das zum laufen gebracht wurde moeglichst bald durch eine HTW mail ersetzen

**Comment by BenSauerlaender** [comment]
Eventuell würde es Sinn machen, dass der Benutzername nicht frei wählbar ist. Sonderen automatisch die Matrikelnummer ist

**Comment by FlyingBaum** [comment]
Neuer Token und neue Gmail Adresse sind drin. Momentan haben nur Leon und ich Zugriff auf secret, token etc. im prod.env file, weil wir es nicht auf dieses public repo pushen wollen. Es funktioniert jedenfalls wie es soll.

Als nächsten Schritt würden wir den Benutzernamen nicht frei wählbar machen und anschließend die Gmail Adresse durch eine HTW Mail ersetzen.

**Comment by BenSauerlaender** [comment]
good job

**Comment by BenSauerlaender** [comment]
Ist die neue email drinn? Wenn ja dann erledigt, oder?

**Comment by BenSauerlaender** [comment]
erledigt.
