### ISSUE TITLE
Kurswahl: Speicher Button fuer die Kurswahl einbauen

### ISSUE THREAD

**Issue by LennoxCode** [modulehandbook/studyplan#18]
es wird zwar gespeichert, jedoch ist es fuer die user expirience besser einen button zu haben

**Comment by BenSauerlaender** [comment]
ist das ein notwendiges feature?

**Comment by LennoxCode** [comment]
ich denke nicht diretk, da dies beim bewegen gespeichert wird. ich dachte aber es ist potenziell gut in der nutzererfahrung zu wissen, dass gespeichert wurde, und dann auf die umfrage weiterzuleiten.
glaube die leute auf die umfrage seite zu nudgen kann recht wichtig sein

**Comment by BenSauerlaender** [comment]
Ich denke am besten genau wie bei #71.
Also so, dass wenn man auf "speichen" drückt kann man erstaml nichts mehr ändern. Und dann gibt es ein "bearbeiten button mit dem man wieder bearbeiten kann.

**Comment by FlyingBaum** [comment]
Both a saving and editing button are implemented, all that's left is some refining.
