### ISSUE TITLE
Kursbelegung: Mehr Informationen in der Belegansicht zeigen (nur noch Frontend)

### ISSUE THREAD

**Issue by LennoxCode** [modulehandbook/studyplan#35]
Zeit wann kurs stattfindet, beschreibung, Prof

**Comment by BenSauerlaender** [comment]
Backend erledigt!
Im ModalCourse model stehen jetzt weiter Informationen zur verfügung,
TODO:
- informationen im frontend anzeigen.

**Comment by FlyingBaum** [comment]
In Progress

**Comment by FlyingBaum** [comment]
Implementiert, eventuell noch paar Verfeinerungen und Formatierungen schöner machen bis Dienstag. ( Nice to have )
