### ISSUE TITLE
Lange Ladezeiten, beim laden von Kursinformationen

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#45]
Wenn man das erstemal im studyplan auf einen Kurs klickt (um Details zu sehen) dauert das teilweise ewig.

Und der "Plan nach Studienordnung" läd glaube ich auch erst dann

**Comment by LennoxCode** [comment]
ich glaube das liegt in diesem fall daran, dass das programm da mit einer externen api kommuniziert, die potenziell langsamer ist. ich bin mir da recht sicher. in dem falle ist das glaube ich ein bottleneck was wir nicht beheben koennen

**Comment by BenSauerlaender** [comment]
related to #89
