### ISSUE TITLE
admin-user anlegen

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#52]
User model anpassen
Admin-page nur für admin sichtbar machen
admin in DB seeden

**Comment by LennoxCode** [comment]
implementiert. es gibt keine moeglichkeit dies zu aendern, und die datenbank startet mit einem admin user. nicht admin user koennen die admin-seite nicht in der navbar sehen, und werden reroutet, wenn sie per adressleite diese ansteuern wollen
