### ISSUE TITLE
Umfrage: Falls noch keine kurse gewählt -> Hinweis anzeigen (Frontend)

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#55]
"noch keine Kurse gewählt" anzeigen, falls noch keine gewählt wurden.

**Comment by BenSauerlaender** [comment]
TODO: Hinweis schöner fromatieren

**Comment by Devianirfan** [comment]
i pulled the code from I56 branch because i think the branch is the newest version of CourseSurvey and I added the no course message. Please review and give feedback.

**Comment by BenSauerlaender** [comment]
Looks great!

I have slightly adjusted the text.
And also adjusted the height of the box.

I will close the issue, and merge your branch into dev.

@Devianirfan In case, you are not happy with my changes, just reopen the Issue and change things again.
