### ISSUE TITLE
Umfrage an s backend anbinden

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#56]

**Comment by LennoxCode** [comment]
es ist an das backend angebunden. Die umfrage seite ist jetzt voll funkontionsfaehig, und laesst ausaehlen warum man die kurse gewaehlt hat, die in courseSelection sind. Diese werden auch im ModalCourse model angepasst, und koennen auch in der admin ansicht eingesehen werden. 
fuer naehere infos den commit log von I65_survey_backend angucken
