### ISSUE TITLE
Ansicht über belegte Kurse hinzufügen (Frontend)

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#57]

**Comment by jimmy080900** [comment]
Soll es einfach nur eine Art Liste sein wo alle Kurse angezeigt werden, die der User ausgewählt hat oder soll es da dann noch bestimmte Funktionen geben ?

**Comment by jimmy080900** [comment]
Ah ok, das ergibt Sinn. Denn wenn es nur die angemeldet Kurse anzeigen soll, würde ich eigentlich denken, dass die Seite mit der Wahlpflichkursbelegung reicht.

**Comment by BenSauerlaender** [comment]
Es gibt ja einen Unterschied zwischen Kursen die man gewählt hat. Und denen, die der algorithmus einem gibt.

**Comment by LennoxCode** [comment]
die seite funktioniert und laesst einen auch kurse abwaehlen
