### ISSUE TITLE
Kurs-belegung: checkbox für wiederholer (teils Frontend)

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#60]
-checkbox hinzufügen
- Hinweis, was die checkbox macht + das alles wahrheitsgemäß sein soll
- ins Model / State /Backend einabuen

**Comment by FlyingBaum** [comment]
Frontend implementiert, Backend auf Rücksprache mit Leo am Freitag

**Comment by LennoxCode** [comment]
wurde implementiert und wird korrekt im backend gespeichert. der toggle bleibt auch zwischen seitenbesuchen erhalten, und ist als default false, bei neuer wahl/ das was bereits in courseSelection steht
