### ISSUE TITLE
Kurs-belegung: Möglichkeit "max. Kursanzahl festlegen" einabuen (teils Frontend)

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#61]
-ins frontend einbauen
-ins backend einbinden

**Comment by LennoxCode** [comment]
Ein button wurde zum erhoehen und reduzieren wurde in die kurswahl eingebaut, und wird im backend gespeichert. dieser kann die groesser als die anzahl der prios und nie kleiner als 0 sein
