### ISSUE TITLE
Studyplan: 0. Semester ausblenden (Frontend)

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#65]

**Comment by jimmy080900** [comment]
Inwiefern ausblenden, im Sinne von dass es gar nicht mehr angezeigt wird ? Denn da werden ja eigentlich alle Kurse angezeigt, die man frei wählen darf für Sprache und Wahlpflicht oder ist dass dann egal, da diese auch angezeigt werden, wenn man auf die einzelnen Oberkategorien im Studyplan klickt ?

**Comment by BenSauerlaender** [comment]
Ja, genau, dass ist ja nicht gewollt, das da alle angezeigt werden, dass war nur ein Test von Leo.
Wenn man wissen will, was man wählen kann muss man auf die Oberkategorien klicken

**Comment by LennoxCode** [comment]
das 0. semester wird jetzt nichtmehr generiert. da diese operation beim erstellen eines studyplans gemaacht wird, muss entsprechend ein neuer generiert werden, um die aenderungen zu sehen
