### ISSUE TITLE
kursumfrage nur einmal machen lassen

### ISSUE THREAD

**Issue by LennoxCode** [modulehandbook/studyplan#71]
momentan kann ich diese umfrage so oft machen wie ich es will, was natuerlich nicht der sinn der sache ist. am Besten ist, wenn man dies einmal macht, und es entsprechend bindend ist

**Comment by ChuChuPL** [comment]
Wie wäre es, dass nachdem man es speichert nur die Ergebnisse gezeigt werden?

**Comment by BenSauerlaender** [comment]
Und am besten dann noch ein button zum "bearbeiten"

**Comment by BenSauerlaender** [comment]
Ergebnisse erst nur im user speichern.
Wenn Stage umspringt: Dann erst in CourseSelection.

Umfrage reset, wenn Kurswahl verändert.

**Comment by LennoxCode** [comment]
Ergebnisse werden jetzt in User gespeichert, und einmal fuer alle ausgwertet. desweiteren kann man die survey nur einmal machen, ausser man aendert die kurswahl noch einmal. nachdem die survey gemacht wurde gibt es einen persistenten hinweis(auch nach neu laden), der fuer das teilnehmen dankt
