### ISSUE TITLE
Umfrage: Auswahlmöglichkeiten ändern

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#75]
Die Auswahlmöglich entschprechend der Kritik ändern.
Mein Vorschlag (so in der Art):

lehrer bedingt -> Ich mag den/die Dozent*in
Kurs ist interessant -> Ich finde das Thema/Inhalt interesannt
Kurs ist einfach -> Ich finde den Inhalt einfach
zeitlich bedingt würde ich raus nehmen
relevant für berufswahl -> *irgendwas mit Vertiefung*

**Comment by jimmy080900** [comment]
Ich hab die Antwortmöglichkeiten jetzt etwas angepasst,  "zeitlich bedingt" habe ich jetzt noch nicht rausgenommen, da ich das möglicherweise mit einer anderen Option ersetzen würde. Wäre da offen für Vorschläge.
Änderungen sind im Branch I75
