### ISSUE TITLE
In Production werden keine mails versand.

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#83]
Es wird keine email versendet, wenn man sich registrieren will. Auch nicht, wenn man Verifizierungslink nochmal senden drückt.
Außerdem gibt es beim registrieren/nochmal senden keinerlei feedback (Ich weiß nicht, ob das zusammen hängt)

Ich habe noch nicht geguckt woran es liegt (code oder server)

**Comment by FlyingBaum** [comment]
Fixed, refresh token ran out too quickly.
