### ISSUE TITLE
Umfrage: Front-end logik überarbeiten

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#86]
Aktuelle Probleme:
- Man kann nicht submiten, wenn other ausgewählt ist, aber leer ist.
- Man kann nur einen Grund angeben
- Standartmäßig ist other ausgewählt
- Wenn man etwas wählt wird das in other gespeichert

**Comment by Devianirfan** [comment]
update: pushed to the branch I86 in Github. In this branch, user is able to send multiple data for Umfrage using check-box. But for the sonstiges part, still don't know how to handle it.

**Comment by BenSauerlaender** [comment]
## Feedback for I86_Frontend_Umfrage_logik_ueberarbeiten:

### First of all: Dont use hard-coded courses:
 - https://github.com/modulehandbook/studyplan/blob/0966c3bedb83ab984d9c118889a057a0b8273f4b/client/src/views/CourseSurvey.vue#L191-L198
 - You can get information about the available courses from "modalcourse/fetchCourses". See CourseSelection.vue for an example how to get the data.

### The survey data should not be stored anymore in courseSelection:
- https://github.com/modulehandbook/studyplan/blob/0966c3bedb83ab984d9c118889a057a0b8273f4b/client/src/views/CourseSurvey.vue#L261-L280
- It should now be stored in user.courseSelection.selectionReasons
- There is no API-route to set/update the courseSelection by now.
- So maybe you can just provide an array in updateCourses() and Leo or me will do the server connection
- The array should look like this: 
https://github.com/modulehandbook/studyplan/blob/0966c3bedb83ab984d9c118889a057a0b8273f4b/model/courseSelection.js#L26-L32
- code is the code of the course
- reason is an array of all selected reasons (teacher, time, interest, easy,  careerRelevant)
- and other is the inputed String in the other field, or if its not selected just undefined

### To fix other: Just dont use the same variable for the text-input-field AND to store the selected reason.
-  tbh: I don't get the code completely, but i think this is what's happened.

### I think you don't need to use all the event stuff. 
- Just use the vue data() function. Variables that are defined there update automatically if the user does an input.

**Comment by LennoxCode** [comment]
Die Radio Buttons wurden durch checkboxes ersetzt, die es moeglich machen eine permutation aus allen gruenden zu waehlen und zu speichern. auch die moeglichkeit sonstige auszufuellen und zu speichern wurde ueberarbeitet. wenn die checkbox daneben gesetzt ist kann diese ausgefuellt werden und wird beim speichern beruecksichtigt. wenn sie erneut getoggled wird wird der inhalt gecleared
