### ISSUE TITLE
Kursbelegung verbessern

### ISSUE THREAD

**Issue by BenSauerlaender** [modulehandbook/studyplan#92]
- Hilfe und heads up text (Drag and drop erwähnen)
- Prio hinzufügen runter
- Hintergrund grün

**Comment by BenSauerlaender** [comment]
Feedback zur neuen Kursbelegung:
- Die +/- Buttons zum einstellen von maxCourses sind kaum zu erkennen Und es ist auch nicht ersichtlich was/warum man da einstellt.
- Prio hinzufügen Button mMn zu groß
- Der Hinweis wird jedes mal angezeigt, wenn man auf die Seite geht.
- Kursbelegung hat als einzige Seite keine Überschrift

**Comment by ChuChuPL** [comment]
Hab alles bis jz umgesetzt.
Was noch fehlt: 

1.  maxCourse an backend (Linh)

nice to have:
1. Hintergrund von dem Hilfe pop up ausblenden(entweder Krist oder ich)

**Comment by ChuChuPL** [comment]
übrig bleibt 
nice to have:

Hintergrund von dem Hilfe pop up ausblenden(entweder Krist oder ich)
